name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
    - name: Login to docker hub
      env: 
          PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u the0ss -p "$PASSWORD"
    - name: Build the Docker image
      run: docker build -t the0ss/sorting-server .
    - name: Publish image to docker hub
      run: docker push the0ss/sorting-server:latest
